name: hello-world
on:
  workflow_dispatch:
    inputs:
      Ok:
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
  my-job1:
    runs-on: ubuntu-latest
    steps:
      - name: my-step1
        run: echo "Bye World!"
